---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kustomize/linkerd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flagger

