---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: terminal
  namespace: default
spec:
  chart:
    spec:
      chart: terminal
      version: '0.2'
      sourceRef:
        kind: HelmRepository
        name: okteto-apps
  interval: 15m0s
  install:
    createNamespace: true
  targetNamespace: terminal
  values:
    ingress:
      enabled: false
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
