---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: default
spec:
  chart:
    spec:
      chart: kyverno
      version: 'v1.3.5'
      sourceRef:
        kind: HelmRepository
        name: kyverno
  interval: 15m0s
  install:
    createNamespace: true
  targetNamespace: kyverno
  values:
    doesntmatter: "different"
