#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: kyverno-hr
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  path: ./clusters/my-cluster/kyverno/helmrelease
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  validation: client
#  dependsOn:
#  - name: flux-system
#    namespace: flux-system
#  releaseName: kyverno
