apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: ef-gitops
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
  exclusionList:
    - "Dependencies do not meet ready condition, retrying in 30s"
